# permissions for end users to edit emails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: email-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-email-operator
    app.kubernetes.io/part-of: kubernetes-email-operator
    app.kubernetes.io/managed-by: kustomize
  name: email-editor-role
rules:
- apiGroups:
  - email-alerts.koperator.rmatto
  resources:
  - emails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - email-alerts.koperator.rmatto
  resources:
  - emails/status
  verbs:
  - get
