apiVersion: email-alerts.koperator.rmatto/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: email
    app.kubernetes.io/instance: email-sample
    app.kubernetes.io/part-of: kubernetes-email-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-email-operator
  name: email-sample
spec:
  senderConfigRef: string
  recipientEmail: string 
  subject: "WARNING | Drink more water!"
  body: "This is an email"
status:
  deliveryStatus: delivered
  messageId: asd01
