apiVersion: email-alerts.koperator.rmatto/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: email
    app.kubernetes.io/instance: email-sample
    app.kubernetes.io/part-of: kubernetes-email-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubernetes-email-operator
  name: email-sample
spec:
  senderConfigRef: emailsenderconfig-mailgun
  recipientEmail: cabinal148@bizatop.com 
  subject: "WARNING | Drink more water!"
  body: "This is a ver DRY email"
